[package]
name = "shorten-path"
version = "0.2.0"
authors = ["Peter Stanko <peter.stanko0@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
